"use client";
import { useEffect, useMemo, useState } from "react";
import PriceStructureChart from "./PriceStructureChart";
import AiAnalysisCard from "./AiAnalysisCard";
import NuplBar from "./NuplBar";
import StockTickerBar from "./StockTickerBar";
import { analyze, avg, scoreDistanceLabel, scoreLabel } from "../lib/analysis";
import { fetchBitcoinNupl, fetchLiveStockMarket, fetchMarket, fetchMultiRsi } from "../lib/api";
import { mapSettledWithConcurrency } from "../lib/concurrency";
import { subscribeLivePrice, type LivePriceStatus } from "../lib/live-price";
import { defaults, displayAsset, rsiLabelByPeriod, staticAssets } from "../lib/config";
import type { BiasItem, MarketData, MultiRsi, NuplReading, Signal } from "../lib/types";

const fallbackSignals:Signal[] = [
  {
    title:"Aguardando mercado",
    summary:"Sem dados suficientes",
    score:0,
    group:"Dados",
    detail:"Os sinais serão calculados quando os candles reais forem carregados.",
  },
];
function freshnessLabel(updatedAt:number|undefined,now:number){if(!updatedAt||!now)return 'ÚLTIMA CONSULTA';const seconds=Math.max(0,Math.floor((now-updatedAt)/1000));if(seconds<60)return `ÚLTIMA CONSULTA HÁ ${seconds}s`;const minutes=Math.floor(seconds/60);if(minutes<60)return `ÚLTIMA CONSULTA HÁ ${minutes}min`;return `ÚLTIMA CONSULTA ÀS ${new Date(updatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}
function readCachedMarket(asset:string,period:string):MarketData|null{try{const saved=localStorage.getItem(`termometro-market-${asset}-${period}`),cached:MarketData|null=saved?JSON.parse(saved):null;return cached&&cached.asset===asset&&cached.candles.length>=55?{...cached,period}:null}catch{return null}}
function marketErrorMessage(error:unknown,asset:string){return error instanceof Error&&error.message?error.message:staticAssets[asset]?`Dados de ${displayAsset(asset)} temporariamente indisponíveis`:"Ativo indisponível ou bloqueado pela fonte"}
export function Termometro(){
 const [ticker,setTicker]=useState("BTC"),[query,setQuery]=useState(""),[period,setPeriod]=useState("1H"),[open,setOpen]=useState<number|null>(null),[assets,setAssets]=useState<string[]>(()=>{if(typeof window==="undefined")return defaults;try{const stored:string[]|null=JSON.parse(localStorage.getItem("termometro-assets")||"null");return stored?[...new Set([...defaults,...stored.filter(asset=>asset!=="SOL")])]:defaults}catch{return defaults}});
 const [market,setMarket]=useState<MarketData|null>(null),[loading,setLoading]=useState(true),[marketError,setMarketError]=useState("");
 const [multiRsi,setMultiRsi]=useState<MultiRsi|null>(null),[multiRsiLoading,setMultiRsiLoading]=useState(true);
 const [nupl,setNupl]=useState<NuplReading|null>(null);
 const [ranking,setRanking]=useState<BiasItem[]>([]);
 const [clock,setClock]=useState(()=>Date.now());
 const [aiRunKey,setAiRunKey]=useState(0);
 const [liveQuote,setLiveQuote]=useState<{asset:string;price:number;updatedAt:number}|null>(null),[liveStatus,setLiveStatus]=useState<LivePriceStatus>("off");
 useEffect(()=>{const timer=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
 const liveEligible=!staticAssets[ticker]&&market?.asset===ticker;
 useEffect(()=>{setLiveQuote(null);if(!liveEligible){setLiveStatus("off");return}return subscribeLivePrice(ticker,{onStatus:setLiveStatus,onPrice:tick=>setLiveQuote({asset:ticker,price:tick.price,updatedAt:Date.now()})})},[ticker,liveEligible]);
 useEffect(()=>{let active=true;async function load(){try{const data=await fetchBitcoinNupl();if(active)setNupl(data)}catch{if(active)setNupl(null)}}load();const timer=window.setInterval(load,600000);return()=>{active=false;window.clearInterval(timer)}},[]);
 const [previousReading,setPreviousReading]=useState<{period:string;score:number}|null>(null);
 const loadMarket=(asset:string,period:string,signal?:AbortSignal)=>{if(staticAssets[asset])return fetchMarket(asset,period,signal);return fetchMarket(asset,period,signal).catch(()=>fetchLiveStockMarket(asset,period,signal))};
 useEffect(()=>{const controller=new AbortController();loadMarket(ticker,'1H',controller.signal).then(data=>{const reading=analyze(data);if(reading&&!controller.signal.aborted)setPreviousReading({period:'1H',score:reading.score})}).catch(()=>{if(!controller.signal.aborted)setPreviousReading(null)});return()=>controller.abort()},[ticker]);
 const [usingCached,setUsingCached]=useState(false);
 useEffect(()=>{if(!market||market.asset!==ticker||usingCached)return;try{localStorage.setItem(`termometro-market-${ticker}-${period}`,JSON.stringify(market))}catch{}},[market,ticker,period,usingCached]);
 const retryMarket=()=>{setLoading(true);setMarketError('');setUsingCached(false);loadMarket(ticker,period).then(data=>{setMarket(data);setMarketError('')}).catch(error=>{const cached=readCachedMarket(ticker,period);setMarket(cached);setUsingCached(!!cached);setMarketError(marketErrorMessage(error,ticker))}).finally(()=>setLoading(false))};
 const [periodFeedback,setPeriodFeedback]=useState(""),[showPeriodHelp,setShowPeriodHelp]=useState(false);
 useEffect(()=>{const controller=new AbortController();loadMarket(ticker,period,controller.signal).then(data=>{if(controller.signal.aborted)return;setMarket(data);setMarketError('');setUsingCached(false);setPeriodFeedback(current=>current?("✓ Termômetro atualizado para "+period):"")}).catch(error=>{if(controller.signal.aborted)return;const cached=readCachedMarket(ticker,period);setMarket(cached);setUsingCached(!!cached);setMarketError(marketErrorMessage(error,ticker))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[ticker,period]);
 useEffect(()=>{const controller=new AbortController();fetchMultiRsi(ticker,controller.signal).then(data=>{if(!controller.signal.aborted)setMultiRsi(data)}).catch(()=>{if(!controller.signal.aborted)setMultiRsi(null)}).finally(()=>{if(!controller.signal.aborted)setMultiRsiLoading(false)});return()=>controller.abort()},[ticker]);
 useEffect(()=>{const controller=new AbortController();mapSettledWithConcurrency(assets,3,(asset)=>loadMarket(asset,period,controller.signal)).then(results=>{if(controller.signal.aborted)return;const next=results.flatMap(result=>{if(result.status!=="fulfilled")return[];const reading=analyze(result.value);return reading?[{asset:result.value.asset,score:reading.score,confidence:reading.confidence,change:reading.change,rsi:reading.rsi}]:[]});setRanking(next.sort((a,b)=>b.score-a.score))});return()=>controller.abort()},[assets,period]);
 const notifyParentAiContext=(asset:string,nextPeriod:string)=>{if(typeof window!=="undefined"&&window.parent!==window)window.parent.postMessage({type:"termometro:ai-context-changed",asset,period:nextPeriod},"https://bitcoiniciantes.github.io")};
 const changePeriod=(nextPeriod:string)=>{if(nextPeriod===period){setPeriodFeedback("✓ "+nextPeriod+" já está selecionado");return}notifyParentAiContext(ticker,nextPeriod);const currentReading=analyze(market);if(currentReading)setPreviousReading({period,score:currentReading.score});setLoading(true);setMarketError("");setUsingCached(false);setPeriodFeedback("Atualizando termômetro para "+nextPeriod+"…");setPeriod(nextPeriod)};
 useEffect(()=>{if(!periodFeedback)return;const timer=window.setTimeout(()=>setPeriodFeedback(""),3200);return()=>window.clearTimeout(timer)},[periodFeedback]);
 const selectAsset=(asset:string)=>{notifyParentAiContext(asset,"1D");setLoading(true);setMarketError("");setUsingCached(false);setPreviousReading(null);if(asset!==ticker)setMultiRsiLoading(true);setPeriod("1D");setTicker(asset)};
 const cleanAsset=(value:string)=>value.trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9.-]/g,"");
 const closeKeyboard=()=>{if(typeof document!=="undefined"&&document.activeElement instanceof HTMLElement)document.activeElement.blur()};
 const analyzeQuery=()=>{const clean=cleanAsset(query);if(clean){selectAsset(clean);setQuery("");closeKeyboard()}};
 const includeAsset=()=>{const clean=cleanAsset(query);if(!clean)return;const next=assets.includes(clean)?assets:[...assets,clean];setAssets(next);localStorage.setItem("termometro-assets",JSON.stringify(next));selectAsset(clean);setQuery("");closeKeyboard()};
 const removeAsset=(asset:string)=>{if(defaults.includes(asset))return;const next=assets.filter(item=>item!==asset);setAssets(next);localStorage.setItem("termometro-assets",JSON.stringify(next));if(ticker===asset)selectAsset(next[0]||"BTC")};
 const analysis=useMemo(()=>analyze(market),[market]); const extreme=analysis?.extreme; const signals=analysis?.signals??fallbackSignals,score=analysis?.score??0,confidence=analysis?.confidence??0,change=analysis?.change??0;
 const livePrice=liveQuote?.asset===ticker?liveQuote.price:undefined;
 const currentPrice=livePrice??market?.candles.at(-1)?.close;
 const chartCandles=useMemo(()=>{if(!market||!livePrice||staticAssets[ticker])return market?.candles??[];const candles=[...market.candles],last=candles.at(-1);if(!last)return candles;candles[candles.length-1]={...last,close:livePrice,high:Math.max(last.high,livePrice),low:Math.min(last.low,livePrice)};return candles},[market,livePrice,ticker]);
 const recent=market?.candles.slice(-21,-1)??[],resistance=recent.length?Math.max(...recent.map(x=>x.high)):0,support=recent.length?Math.min(...recent.map(x=>x.low)):0;
 const tr=market?.candles.slice(-15).map((x,i,a)=>i?Math.max(x.high-x.low,Math.abs(x.high-a[i-1].close),Math.abs(x.low-a[i-1].close)):x.high-x.low)??[];
 const atrAbs=tr.length?avg(tr.slice(-14)):0,entry=resistance?resistance*1.002:0,stop=entry&&atrAbs?entry-atrAbs*1.5:0,target=entry&&stop?entry+(entry-stop)*2.5:0;
 const volumeRatio=market&&market.candles.length>21?market.candles.at(-1)!.volume/avg(market.candles.slice(-21,-1).map(x=>x.volume)):0;
 const currency=staticAssets[ticker]?.currency??"USDT";
 const displayName=displayAsset(ticker);
 const fmt=(value:number|undefined)=>value?`${currency} ${value.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`:"—";
 const pct=(value:number)=>currentPrice&&value?`${value>=currentPrice?"+":""}${((value/currentPrice-1)*100).toFixed(2)}%`:"—"; const entryDistance=currentPrice&&entry?(entry/currentPrice-1)*100:0,supportDistance=currentPrice&&support?(support/currentPrice-1)*100:0;
 const showPlan=!!analysis&&score>=20&&entryDistance<=15;
 const planStatus=!analysis?"SEM DADOS":score<=-20?"PRESSÃO DE VENDA":score<20?"AGUARDAR":entryDistance>15?"GATILHO DISTANTE":entryDistance>5?"EM OBSERVAÇÃO":"PRÓXIMO DO GATILHO";
 const planTone=score<=-20?"sell":score<20||entryDistance>15?"wait":"ready";
 const planMessage=!analysis?"Aguardando dados suficientes.":score<=-20?"Plano de compra suspenso: pressão vendedora predominante.":score<20?"Leitura neutra. Nenhuma entrada válida neste momento.":entryDistance>15?`Rompimento a ${entryDistance.toFixed(2)}% do preço atual; cenário ainda distante.`:entryDistance>5?`Ativo a ${entryDistance.toFixed(2)}% do gatilho; mantenha em observação.`:"Gatilho próximo; aguarde confirmação do fechamento.";
 const patternTitle=analysis&&signals[1]?.score>0?signals[1].summary:"Sem padrão confirmado";
 const label=scoreLabel(score);
 const scoreExplanation=score>=20?"Convergência positiva, com risco controlado.":score<=-20?"Pressão vendedora predominante; evite antecipar reversão.":`${score>=10?"Sinais mistos com viés positivo.":score<=-10?"Sinais mistos com viés negativo.":"Sinais equilibrados."} ${scoreDistanceLabel(score)}`;
 const toneClass=score>=20?"tonePositive":score<=-20?"toneNegative":"toneNeutral";
 const radarItems=useMemo(()=>[...ranking.filter(item=>item.asset!=="MSTR").map(item=>({...item,available:true})),...assets.filter(asset=>asset!=="MSTR"&&!ranking.some(item=>item.asset===asset)).map(asset=>({asset,score:0,confidence:0,change:0,rsi:undefined,available:false}))],[ranking,assets]);
 const availablePeriods=staticAssets[ticker]?["15M","1H","4H","1D","1S","1M"]:["15M","1H","4H","1D","1S","1M"];
 const selectedRsi=multiRsi?.rows.find(row=>row.label===rsiLabelByPeriod[period]);
 const selectedRsiTone=!selectedRsi?"neutral":selectedRsi.value>=55?"high":selectedRsi.value<=45?"low":"neutral";
 const selectedRsiStatus=!selectedRsi?"AGUARDANDO":selectedRsi.value>=80?"SOBRECOMPRA":selectedRsi.value<=25?"SOBREVENDA":selectedRsi.value>=55?"ALTA":selectedRsi.value<=45?"BAIXA":"NEUTRO";
 const liveQuoteAge=liveQuote?.asset===ticker?Math.max(0,Math.floor((clock-liveQuote.updatedAt)/1000)):null,cryptoLive=!staticAssets[ticker]&&liveStatus==="live"&&!!livePrice&&liveQuoteAge!==null&&liveQuoteAge<=5,sourceLabel=staticAssets[ticker]?'YAHOO FINANCE':cryptoLive?'BINANCE • AO VIVO':liveStatus==="reconnecting"?'BINANCE • RECONECTANDO':'BINANCE',freshnessBase=freshnessLabel(market?.updatedAt,clock),freshness=staticAssets[ticker]?freshnessBase.replace('ÚLTIMA CONSULTA','DADO ATUALIZADO'):liveQuoteAge!==null?`${cryptoLive?"COTAÇÃO AO VIVO • STREAM CONECTADO":"ÚLTIMA COTAÇÃO AO VIVO"}`:freshnessBase;
 const aiMarketData=`Fonte: ${sourceLabel}. Preço atual: ${fmt(currentPrice)}. Variação no candle ${period}: ${change>=0?"+":""}${change.toFixed(2)}%. Termômetro: ${label} (${score>0?"+":""}${score}/100), confiança ${confidence}%. RSI: ${selectedRsi?selectedRsi.value.toFixed(1):"indisponível"} (${selectedRsiStatus}). Suporte: ${fmt(support)}. Resistência: ${fmt(resistance)}. Volume: ${volumeRatio?`${volumeRatio.toFixed(2)}× média`:"indisponível"}.`;
 return <main>
  <div className='marketFreshness'><span className='sourceStatus'><i/>{loading?'BUSCANDO MERCADO':marketError?'FONTE INDISPONÍVEL':sourceLabel}</span>{!loading&&market&&<span className='freshness'>{freshness}</span>}<button type='button' onClick={retryMarket} disabled={loading} aria-label='Consultar dados novamente' title='Consultar dados novamente'>↻</button></div>
  <header><a className="brand" href="#inicio" onClick={event=>{event.preventDefault();window.scrollTo({top:0,behavior:"smooth"});}} aria-label="Voltar ao início do Termômetro" title="Voltar ao início"><b>T°</b><span>TERMÔMETRO<small>ANÁLISE DE MERCADO</small></span></a><nav aria-label="Menu principal"><a href="#painel">Painel</a><a href="#metodo">Metodologia</a><a href="#regras">Regras</a><a className="externalNav" href="https://bitcoiniciantes.github.io/estudebitcoin/" target="_blank" rel="noopener noreferrer">Estude Bitcoin <span aria-hidden="true">↗</span></a></nav><span className="live"><i/> {loading?"BUSCANDO MERCADO":marketError?"FONTE INDISPONÍVEL":staticAssets[ticker]?`${displayName} • YAHOO FINANCE`:cryptoLive?"COTAÇÃO AO VIVO • BINANCE":"DADOS REAIS • BINANCE"}</span></header>
  <section className="analysisDesk workspace" id="painel">
  <div className="analysisColumn analysisLeft">
    <div className="workspaceMain">
    <div className="deskTop">
      <div className="deskAsset"><button type="button" className="assetIcon assetAiButton" onClick={() => { if (window.parent !== window) { window.parent.postMessage({ type: "termometro:open-estudebitcoin-ai", asset: ticker, period, marketData: aiMarketData }, "https://bitcoiniciantes.github.io"); return; } setAiRunKey(Date.now()); window.setTimeout(() => document.getElementById("analista-digital")?.scrollIntoView({ behavior: "smooth", block: "start" }), 30); }} disabled={!analysis || loading || !currentPrice} aria-label="Abrir Analista Digital e gerar leitura">IA</button><div><span className="eyebrow">ATIVO EM ANÁLISE</span><h1>{displayName}<small>/{currency}</small></h1></div></div>
      <div className={`deskQuote ${cryptoLive?"quoteLive":""}`}><span>{cryptoLive?"COTAÇÃO AO VIVO":"ÚLTIMO PREÇO"}</span><b>{fmt(currentPrice)}</b><small className={change<0?"down":""}>{analysis?`${change>=0?"+":""}${change.toFixed(2)}% no candle`:marketError||"Carregando..."}</small></div>
      <div className={`quickScale ${loading?"isLoading":""}`} role="img" aria-label={`Viés rápido: ${loading?"carregando":score}`}><div className="quickScaleHead"><span>VIÉS RÁPIDO</span><b>{loading?"CARREGANDO":`${score>0?"+":""}${score}`}</b></div><div className="quickScaleTrack"><i style={{left:loading?"50%":`${(score+100)/2}%`}}/></div><div className="quickScaleLabels"><span>-100<br/>Venda</span><span>0<br/>Neutro</span><span>+100<br/>Compra</span></div></div>
      <div className="desktopPeriodPrompt"><div className="desktopPeriodGuide"><div><span>ESCOLHA O PERÍODO</span><button type="button" onClick={()=>setShowPeriodHelp(value=>!value)} aria-expanded={showPeriodHelp} aria-label="Explicar períodos">i</button></div><small>O resultado muda conforme o período.</small>{showPeriodHelp&&<p>Períodos curtos reagem mais rápido e têm mais ruído. Períodos longos mostram tendências mais consistentes.</p>}</div><div className="periods">{availablePeriods.map(p=><button key={p} onClick={()=>changePeriod(p)} className={period===p?"active":""} aria-pressed={period===p} aria-label={`Consultar período ${p}`}>{p}</button>)}</div>{periodFeedback&&<div className={`desktopPeriodFeedback ${periodFeedback.startsWith("✓")?"done":""}`} role="status" aria-live="polite">{periodFeedback}</div>}</div>
    </div>
    <div className='mobileTopPeriods'><span>PERÍODO DA ANÁLISE</span><div className='periods'>{availablePeriods.map(p=><button key={p} onClick={()=>changePeriod(p)} className={period===p?'active':''} aria-pressed={period===p} aria-label={`Consultar período ${p}`}>{p}</button>)}</div>{periodFeedback&&<small role='status' aria-live='polite'>{periodFeedback}</small>}</div>
    {previousReading&&!loading&&<div className='mobilePeriodComparison'><PeriodComparison previous={previousReading} current={{period,score}}/></div>}
    {marketError&&<div className={'marketRecovery '+(usingCached?'cached':'failed')} role='alert'><div><b>{usingCached?'DADO SALVO':'NÃO FOI POSSÍVEL ATUALIZAR'}</b><span>{usingCached?'A fonte não respondeu. Exibindo o último dado salvo.':marketError}{usingCached&&market?.updatedAt?` Atualizado em ${new Date(market.updatedAt).toLocaleString('pt-BR')}.`:''}</span></div><button type='button' onClick={retryMarket} disabled={loading}>{loading?'Tentando…':'Tentar novamente'}</button></div>}
    <div className="desktopSearchRow">
    <form className="assetSearch" onSubmit={e=>{e.preventDefault();analyzeQuery()}}><label>BUSCAR ATIVO</label><div><input aria-label="Código do ativo" value={query} onChange={e=>setQuery(e.target.value)} placeholder="BTC" type="search" enterKeyHint="search" autoCapitalize="characters" spellCheck={false} autoComplete="off" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();analyzeQuery();e.currentTarget.blur()}}}/><button type="submit">Analisar</button><button type="button" className="includeButton" onClick={includeAsset}>+ Incluir</button></div></form>
    <div className={`rsiMirror ${selectedRsiTone}`} role="status" aria-live="polite"><span>RSI</span><b>{selectedRsi?selectedRsi.value.toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1}):"—"}</b><em>{selectedRsiStatus}</em></div>
    {previousReading&&!loading&&<div className='desktopPeriodComparison'><PeriodComparison previous={previousReading} current={{period,score}}/></div>}
    </div>
    <StockTickerBar onSelect={selectAsset} />
    <div className="biasBoard"><div className="biasHead"><span>RADAR COMPRA × VENDA</span><button type="button" className="biasAiButton" onClick={() => { if (window.parent !== window) { window.parent.postMessage({ type: "termometro:open-estudebitcoin-ai", asset: ticker, period, marketData: aiMarketData }, "https://bitcoiniciantes.github.io"); return; } setAiRunKey(Date.now()); window.setTimeout(() => document.getElementById("analista-digital")?.scrollIntoView({ behavior: "smooth", block: "start" }), 30); }} aria-label={`Análise com IA para ${displayName}`} title={`Análise com IA: ${displayName}`}><span aria-hidden="true">✦</span> Análise com IA</button></div><div className="biasList">{radarItems.map((item)=>{const side=!item.available?"SEM DADOS":item.score>=20?"COMPRA":item.score<=-20?"VENDA":item.score>=10?"NEUTRO ↑":item.score<=-10?"NEUTRO ↓":"NEUTRO",sideTone=!item.available?"sem-dados":item.score>=20?"compra":item.score<=-20?"venda":item.score>=10?"neutro-alta":item.score<=-10?"neutro-baixa":"neutro",toneColor=!item.available?"#718079":item.score>=20?"#54b85a":item.score<=-20?"#e2555d":"#c39a45",ringDegrees=(Math.max(-100,Math.min(100,item.score))+100)*1.8;return <div key={item.asset} className={`biasItem ${sideTone} ${ticker===item.asset?"selected":""}`}><button type="button" className="biasSelect" onClick={()=>selectAsset(item.asset)} aria-pressed={ticker===item.asset}><span className="biasRsi">RSI={item.rsi===undefined?"—":Math.round(item.rsi)}</span><span className="biasGauge" style={{background:`conic-gradient(from 180deg,${toneColor} ${ringDegrees}deg,#26312d ${ringDegrees}deg 360deg)`}}><strong>{item.available?`${item.score>0?"+":""}${item.score}`:"—"}</strong><b>{displayAsset(item.asset)}</b></span><span className="biasSide">{side.replace(/[↑↓]/u,"")}<em>{side.includes("↑")?"↑":side.includes("↓")?"↓":""}</em></span></button>{!defaults.includes(item.asset)&&<button className="biasRemove" onClick={()=>removeAsset(item.asset)} aria-label={`Remover ${displayAsset(item.asset)}`} title={`Remover ${displayAsset(item.asset)}`}>×</button>}</div>})}</div><p>Viés técnico comparativo; não representa ordem de entrada.</p></div>
  </div>
    <div className="mobileChartPeriods" aria-label="Período do gráfico"><span>PERÍODO DO GRÁFICO</span><div className="periods">{availablePeriods.map(p=><button key={p} type="button" onClick={()=>changePeriod(p)} className={period===p?"active":""} aria-pressed={period===p} aria-label={`Consultar período ${p}`}>{p}</button>)}</div></div>
    <article className="card chart"><div className="cardTitle chartTitle"><div><span>ESTRUTURA DE PREÇO</span><b>{patternTitle}</b></div>{ticker==="BTC"&&nupl&&<NuplBar nupl={nupl}/>}<div className="chartPeriodSwitch" aria-label="Período do gráfico"><span>TIME FRAME</span><div>{availablePeriods.map(p=><button key={`chart-${p}`} type="button" onClick={()=>changePeriod(p)} className={period===p?"active":""} aria-pressed={period===p}>{p}</button>)}</div></div></div><PriceStructureChart asset={displayName} candles={chartCandles} currentPrice={currentPrice ?? 0} currency={currency} loading={loading} period={period} resistance={resistance} support={support}/><div className="chartFoot"><span><i className="dot candleUpDot"/>Alta: fechamento ≥ abertura</span><span><i className="dot candleDownDot"/>Baixa: fechamento &lt; abertura</span><span>Volume <b>{volumeRatio?`${volumeRatio.toFixed(2)}× média`:"—"}</b></span><span className="chartPurpose">Corpo: abertura–fechamento · Pavio: mínima–máxima · Níveis calculados com candles concluídos.</span></div></article>
  <article className="card signals" id="regras"><Title kicker="RAIO-X DA NOTA" title={`${signals.filter(signal=>!signal.context).length} sinais de nota + ${signals.filter(signal=>signal.context).length} contextos`} extra={<span className="sum">SOMA: <b>{score>0?"+":""}{score}</b></span>}/><div className="signalList">{signals.map((signal,index)=><button type="button" key={signal.title} onClick={()=>setOpen(open===index?null:index)} className={open===index?"opened":""} aria-expanded={open===index}><span className={`sign ${signal.context?"context":signal.score===0?"zero":signal.score>0?"positive":"negative"}`}>{signal.context?"CTX":<>{signal.score>0?"+":""}{signal.score}</>}</span><span className="signalText"><b>{signal.title}</b><small>{signal.summary}</small>{open===index&&<em>{signal.detail}</em>}</span><span className={`group ${signal.context?"contextGroup":""}`}>{signal.group}</span><span className="chev" aria-hidden="true">›</span></button>)}</div></article>
  </div>
  <div className="analysisColumn analysisRight">
    <article className={`card thermo heroThermo thermoTone ${toneClass}`}><div className="mobilePeriods periodPrompt"><div className="periodGuide"><div><span>ESCOLHA O PERÍODO DA ANÁLISE</span><button type="button" onClick={()=>setShowPeriodHelp(value=>!value)} aria-expanded={showPeriodHelp} aria-label="Explicar períodos">i</button></div><small>O resultado muda conforme o período.</small>{showPeriodHelp&&<p>Períodos curtos reagem mais rápido e têm mais ruído. Períodos longos mostram tendências mais consistentes.</p>}</div><div className="periods">{availablePeriods.map(p=><button key={p} onClick={()=>changePeriod(p)} className={period===p?"active":""} aria-pressed={period===p} aria-label={`Consultar período ${p}`}>{p}</button>)}</div>{periodFeedback&&<div className={`periodFeedback ${periodFeedback.startsWith("✓")?"done":""}`} role="status" aria-live="polite">{periodFeedback}</div>}</div><Title kicker="TERMÔMETRO DO ATIVO" title={loading?`Carregando ${displayName}…`:`Leitura consolidada · ${displayName}`} extra={<button type="button" className="info" title="Regras fixas, sem IA" aria-label="Sobre as regras do Termômetro">i</button>}/><div className="scoreRing" style={{"--score":`${(score+100)*1.8}deg`} as React.CSSProperties}><div><b>{score>0?"+":""}{score}</b><span>DE 100</span><strong className="heroAsset">{ticker==="BTC"&&<i aria-hidden="true">₿</i>}{displayAsset(ticker)}</strong></div></div><span className={`heroRsi ${selectedRsiTone}`}>RSI = <b>{selectedRsi ? Math.round(selectedRsi.value) : "—"}</b></span><h3>{label}</h3><p>{scoreExplanation}</p><div className="scale"><div className="scaleTrack"><i style={{left:`${(score+100)/2}%`}}/></div><div><span>-100<br/>Venda</span><span>0<br/>Neutro</span><span>+100<br/>Compra</span></div></div><div className="confidence"><span>Concordância dos sinais</span><b>{confidence}%</b><div><i style={{width:`${confidence}%`}}/></div></div></article>
    {extreme&&<article className={`card extremeCard ${extreme.tone}`}><Title kicker="EXTREMO TÉCNICO" title={extreme.status} extra={<span className="extremePeriod">{period}</span>}/><div className="extremeBody"><p>{extreme.summary}</p><div className="extremeMetrics"><span><small>RSI WILDER</small><b>{extreme.rsi.toFixed(1)}</b></span><span><small>FORÇA ADX</small><b>{extreme.adx.toFixed(1)}</b></span><span><small>DISTÂNCIA</small><b>{extreme.atrDistance.toFixed(1)} ATR</b></span></div><div className="extremeContext"><span>{extreme.adx>=25?'TENDÊNCIA FORTE':'TENDÊNCIA FRACA'}</span><span>{extreme.divergence==='bullish'?'DIVERGÊNCIA DE ALTA':extreme.divergence==='bearish'?'DIVERGÊNCIA DE BAIXA':'SEM DIVERGÊNCIA'}</span></div><small className="extremeDetail">{extreme.detail}</small></div></article>}
    <RsiGeneralPanel asset={displayName} data={multiRsi} loading={multiRsiLoading}/>
    <AiAnalysisCard
      key={`${ticker}-${period}`}
      autoRunKey={aiRunKey}
      disabled={!analysis || loading || !currentPrice}
      payload={{
        asset: displayName,
        period,
        currentPrice: currentPrice ?? 0,
        score,
        confidence,
        change,
        support,
        resistance,
        entry,
        stop,
        target,
        volumeRatio,
        multiRsi: multiRsi ? { general: multiRsi.general, bullCount: multiRsi.bullCount, bearCount: multiRsi.bearCount, signal: multiRsi.signal } : null,
        signals: signals.map(({ title, summary, score: signalScore, group, context }) => ({ title, summary, score: signalScore, group, context })),
      }}
    />
    <article className="card levels"><Title kicker="PLANO TÉCNICO" title="Cenário condicional"/><div className={`planStatus ${planTone}`}><span>STATUS DO CENÁRIO</span><b>{planStatus}</b><p>{planMessage}</p></div>{showPlan?<><div className="level target"><span>ALVO PROJETADO</span><b>{fmt(target)}</b><small>{pct(target)}</small></div><div className="level entry"><span>ROMPIMENTO / ENTRADA CONDICIONAL</span><b>{fmt(entry)}</b><small>{entryDistance.toFixed(2)}% do preço atual</small></div><div className="level stop"><span>INVALIDAÇÃO / STOP APÓS ENTRADA</span><b>{fmt(stop)}</b><small>{pct(stop)}</small></div><div className="risk"><span>RISCO : RETORNO</span><b>{entry&&stop?"1 : 2,5":"—"}</b></div></>:<><div className="level currentLevel"><span>PREÇO ATUAL</span><b>{fmt(currentPrice)}</b><small>referência</small></div><div className={`level ${score<=-20?"stop":"entry"}`}><span>{score<=-20?"SUPORTE DE REFERÊNCIA":"RESISTÊNCIA DE REFERÊNCIA"}</span><b>{fmt(score<=-20?support:resistance)}</b><small>{score<=-20?pct(support):pct(resistance)}</small></div><div className="distanceNote"><span>{score<=-20?"DISTÂNCIA ATÉ O SUPORTE":"DISTÂNCIA ATÉ O ROMPIMENTO"}</span><b>{score<=-20?`${supportDistance.toFixed(2)}%`:`${entryDistance.toFixed(2)}%`}</b></div></>}<p className="disclaimer">Níveis usam candles concluídos, estrutura e ATR. Conteúdo educacional, não é recomendação.</p></article>
  </div>
</section>
  <section className="method" id="metodo"><div><span className="eyebrow">COMO A NOTA NASCE</span><h2>Sem palpite.<br/>Sem caixa-preta.</h2></div><div className="methodSteps">{[["01","Detectamos","Pivôs, linhas, compressões e padrões geométricos."],["02","Confirmamos","Momentum, tendência, volume e volatilidade validam o cenário."],["03","Pontuamos","Cada regra soma ou subtrai pontos com pesos públicos."],["04","Explicamos","Você audita cada ponto e sabe o que muda a leitura."]].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <footer><span><b>T°</b> TERMÔMETRO</span><p>Motor determinístico • Interpretação opcional assistida por IA</p><span data-goatcounter-total hidden aria-label="Total de acessos"></span><small>PILOTO v0.2</small></footer>
 </main>
}
function PeriodComparison({previous,current}:{previous:{period:string;score:number};current:{period:string;score:number}}){const state=(score:number)=>score>=20?{label:'COMPRA',tone:'buy'}:score<=-20?{label:'VENDA',tone:'sell'}:score>=10?{label:'NEUTRO ↑',tone:'neutral'}:score<=-10?{label:'NEUTRO ↓',tone:'neutral'}:{label:'NEUTRO',tone:'neutral'},before=state(previous.score),after=state(current.score),signed=(score:number)=>`${score>0?'+':''}${score}`;return <div className='periodComparison' role='status' aria-live='polite'><span className={'periodState '+before.tone}><b>{before.label}</b><strong>{signed(previous.score)}</strong><small>{previous.period}</small></span><i aria-hidden='true'>→</i><span className={'periodState '+after.tone}><b>{after.label}</b><strong>{signed(current.score)}</strong><small>{current.period}</small></span></div>}
function RsiGeneralPanel({asset,data,loading}:{asset:string;data:MultiRsi|null;loading:boolean}){const status=(v:number)=>v>=80?"Sobrecompra":v<=25?"Sobrevenda":v>=55?"Alta":v<=45?"Baixa":"Neutro",tone=(v:number)=>v>=55?"high":v<=45?"low":"neutral",gauge=(v:number)=>"■".repeat(Math.round(v/10))+"□".repeat(10-Math.round(v/10)),rows=data?[...data.rows,{label:"GERAL",value:data.general,previous:data.previousGeneral}]:[];return <article className="rsiGeneral card" aria-busy={loading}><div className="rsiTitle">{asset} <span>•</span> RSI GERAL PRO</div><div className="rsiGrid rsiHeader"><span>TF</span><span>RSI</span><span>LEITURA</span><span>DIR.</span></div>{loading?<div className="rsiEmpty">CALCULANDO 6 PERÍODOS…</div>:!data?<div className="rsiEmpty">DADOS MULTI-TEMPORAIS INDISPONÍVEIS</div>:<>{rows.map(row=><div className={`rsiGrid rsiRow ${row.label==="GERAL"?"general":""}`} key={row.label}><b>{row.label}</b><strong className={tone(row.value)}>{row.value.toFixed(1)}</strong><span className={tone(row.value)}>{status(row.value)}</span><i className={row.value>=row.previous?"up":"down"}>{row.value>=row.previous?"▲":"▼"}</i></div>)}<div className="rsiGrid consensus"><b>CONSENSO</b><strong>{data.bullCount}▲</strong><span>{Math.round(data.bullCount/data.rows.length*100)}% alta</span><i>{data.bearCount}▼</i></div><div className={`rsiSummary ${tone(data.general)}`}><b>SINAL</b><span>{data.signal}</span></div><div className={`rsiSummary force ${tone(data.general)}`}><b>FORÇA</b><span>{gauge(data.general)}  {data.general.toFixed(1)}</span></div><small>◉ DADOS DE MERCADO • atualização automática</small></>}</article>}export default function Home(){return <Termometro/>}
function Title({kicker,title,extra}:{kicker:string,title:string,extra?:React.ReactNode}){return <div className="cardTitle"><div><span>{kicker}</span><b>{title}</b></div>{extra}</div>}
