"use client";
import { useEffect, useMemo, useState } from "react";

type Signal=[string,string,number,string,string];
type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
type MarketData={asset:string;pair:string;source:string;updatedAt:number;candles:Candle[]};
const fallbackSignals:Signal[] = [
  ["Tendência primária","MM20 acima da MM50",16,"Tendência","A média de 20 períodos está acima da média de 50, com ambas inclinadas para cima."],
  ["Triângulo ascendente","Compressão + topos alinhados",20,"Padrão","Foram encontrados 3 testes de resistência e fundos progressivamente mais altos."],
  ["Força relativa","IFR em 61,4",8,"Momentum","Momentum positivo sem entrar na zona de sobrecompra. Faixa ideal configurada: 55–68."],
  ["Confirmação por volume","1,7× a média",13,"Volume","O volume recente supera a média de 20 períodos e fortalece o rompimento."],
  ["Volatilidade elevada","ATR em expansão",-9,"Risco","A amplitude média cresceu 18% em cinco sessões. O risco exige stop mais largo."],
  ["Resistência próxima","Distância de 1,2%",-7,"Estrutura","Há oferta relevante perto do preço atual. A nota melhora após fechamento acima dela."],
];
const fallbackCandles=[42,46,44,49,47,52,50,55,53,57,54,59,58,62,60,64,61,67,65,70,68,73,71,77,75,80,78,83,81,86,84,89];
const defaults=["BTC","ETH","LINK","AVAX","SOL","MSTR"];
const avg=(v:number[])=>v.reduce((a,b)=>a+b,0)/Math.max(v.length,1);
function analyze(data:MarketData|null):{signals:Signal[];score:number;confidence:number;change:number}|null{
 if(!data||data.candles.length<55)return null; const c=data.candles, closes=c.map(x=>x.close), last=closes.at(-1)!;
 const sma20=avg(closes.slice(-20)),sma50=avg(closes.slice(-50));
 const deltas=closes.slice(-15).map((x,i)=>x-closes[closes.length-16+i]); const gains=avg(deltas.map(x=>Math.max(x,0))),losses=avg(deltas.map(x=>Math.max(-x,0))); const rsi=losses===0?100:100-(100/(1+gains/losses));
 const vol20=avg(c.slice(-21,-1).map(x=>x.volume)),volRatio=c.at(-1)!.volume/Math.max(vol20,1);
 const atr=avg(c.slice(-14).map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[c.length-15+i].close),Math.abs(x.low-c[c.length-15+i].close)):x.high-x.low))/last*100;
 const highs=c.slice(-20).map(x=>x.high),lows=c.slice(-20).map(x=>x.low),compression=(Math.max(...highs.slice(-10))-Math.min(...lows.slice(-10)))/(Math.max(...highs)-Math.min(...lows)); const ascending=avg(lows.slice(-5))>avg(lows.slice(0,5));
 const trend=sma20>sma50?18:-18,momentum=rsi>=55&&rsi<=70?12:rsi>70?-6:rsi<40?-12:2,volume=volRatio>=1.25?12:volRatio<.7?-5:3,pattern=compression<.72?(ascending?18:8):0,risk=atr>7?-12:atr>4?-6:4;
 const signals:Signal[]=[["Tendência primária",`MM20 ${sma20>sma50?"acima":"abaixo"} da MM50`,trend,"Tendência",`MM20: ${sma20.toFixed(2)} • MM50: ${sma50.toFixed(2)}.`],["Compressão de preço",compression<.72?(ascending?"Estrutura ascendente detectada":"Amplitude em contração"):"Sem compressão relevante",pattern,"Padrão",`A amplitude recente equivale a ${(compression*100).toFixed(0)}% da janela de 20 candles.`],["Força relativa",`RSI em ${rsi.toFixed(1)}`,momentum,"Momentum","RSI de 14 períodos calculado pelos fechamentos reais."],["Confirmação por volume",`${volRatio.toFixed(2)}× a média`,volume,"Volume","Volume do candle atual comparado à média dos 20 anteriores."],["Risco por volatilidade",`ATR em ${atr.toFixed(2)}%`,risk,"Risco","ATR de 14 períodos normalizado pelo preço atual."]];
 const score=Math.max(-100,Math.min(100,signals.reduce((a,s)=>a+s[2],0))),agreement=signals.filter(s=>Math.sign(s[2])===Math.sign(score)).length/signals.length; return{signals,score,confidence:Math.round(55+agreement*35),change:(last/closes.at(-2)!-1)*100};
}

export default function Home(){
 const [ticker,setTicker]=useState("BTC"),[query,setQuery]=useState("BTC"),[period,setPeriod]=useState("1D"),[open,setOpen]=useState<number|null>(1),[assets,setAssets]=useState<string[]>(()=>{if(typeof window==="undefined")return defaults;try{return JSON.parse(localStorage.getItem("termometro-assets")||"null")||defaults}catch{return defaults}}),[newAsset,setNewAsset]=useState("");
 const [market,setMarket]=useState<MarketData|null>(null),[loading,setLoading]=useState(true),[marketError,setMarketError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch(`/api/market?asset=${ticker}&period=${period}`,{signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setMarket(body)}).catch(e=>{if(e.name!=="AbortError"){setMarket(null);setMarketError(e.message)}}).finally(()=>setLoading(false));return()=>controller.abort()},[ticker,period]);
 const selectAsset=(asset:string)=>{setLoading(true);setMarketError("");setTicker(asset);setQuery(asset)};
 const addAsset=()=>{const clean=newAsset.trim().toUpperCase().replace(/[^A-Z0-9.-]/g,"");if(!clean)return;const next=assets.includes(clean)?assets:[...assets,clean];setAssets(next);localStorage.setItem("termometro-assets",JSON.stringify(next));selectAsset(clean);setNewAsset("")};
 const analysis=useMemo(()=>analyze(market),[market]);
 const signals=analysis?.signals??fallbackSignals,score=analysis?.score??0,confidence=analysis?.confidence??0,change=analysis?.change??0;
 const candleValues=market?.candles.slice(-32).map(x=>x.close)??fallbackCandles;
 const minC=Math.min(...candleValues),maxC=Math.max(...candleValues),candleHeights=candleValues.map(x=>20+((x-minC)/Math.max(maxC-minC,1))*65);
 const currentPrice=market?.candles.at(-1)?.close;
 const label=score>=55?"COMPRA FORTE":score>=20?"COMPRA":score>-20?"NEUTRO":score>-55?"VENDA":"VENDA FORTE";
 return <main>
  <header><a className="brand"><b>T°</b><span>TERMÔMETRO<small>mercado em leitura</small></span></a><nav><a href="#painel">Painel</a><a href="#metodo">Metodologia</a><a href="#regras">Regras</a></nav><span className="live"><i/> {loading?"BUSCANDO MERCADO":marketError?"FONTE INDISPONÍVEL":"DADOS REAIS • BINANCE"}</span></header>
  <section className="hero" id="painel"><span className="eyebrow">ANÁLISE TÉCNICA • SEM IA • 100% EXPLICÁVEL</span><div className="heroRow"><div><h1>O mercado deixa pistas.<br/><em>Nós medimos a temperatura.</em></h1><p>Convergência de tendência, padrões, momentum, volume e risco em uma única leitura auditável.</p></div><form onSubmit={e=>{e.preventDefault();if(query.trim())selectAsset(query.trim().toUpperCase())}}><label>ANALISAR ATIVO</label><div><span>⌕</span><input aria-label="Código do ativo" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: BTC"/><button>Analisar →</button></div><small>Criptomoedas e ativos relacionados em uma mesma mesa de leitura.</small></form></div><div className="watchDesk"><div className="watchTop"><div><span className="watchLabel">RADAR RÁPIDO</span><b>Seus ativos</b></div><div className="addAsset"><input aria-label="Novo ativo" value={newAsset} onChange={e=>setNewAsset(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addAsset()}}} placeholder="Adicionar código..."/><button onClick={addAsset}>+ Incluir ativo</button></div></div><div className="assetChips">{assets.map((asset,i)=><button key={asset} onClick={()=>selectAsset(asset)} className={ticker===asset?"selected":""}><span className={`coin coin${i%6}`}>{asset.slice(0,1)}</span><b>{asset}</b><small>{asset==="MSTR"?"NASDAQ":"USD"}</small>{ticker===asset&&<i>EM ANÁLISE</i>}</button>)}</div></div></section>
  <section className="dashboard"><div className="assetHead"><div className="identity"><span className="assetIcon">{ticker.slice(0,2)}</span><div><h2>{ticker}</h2><p>{ticker==="MSTR"?"MicroStrategy • NASDAQ":"Criptoativo • par USD"}</p></div></div><div className="quote"><b>{currentPrice?`$ ${currentPrice.toLocaleString("pt-BR",{maximumFractionDigits:currentPrice>100?2:4})}`:"—"}</b><span className={change<0?"down":""}>{analysis?`${change>=0?"+":""}${change.toFixed(2)}% no candle`:marketError||"Carregando..."}</span></div><div className="periods">{["1H","4H","1D","1S"].map(p=><button key={p} onClick={()=>{setLoading(true);setMarketError("");setPeriod(p)}} className={period===p?"active":""}>{p}</button>)}</div><span className="updated">{market?`Fonte: ${market.source}`:"Aguardando dados"}</span></div>
   <div className="grid">
    <article className="card chart"><Title kicker="ESTRUTURA DE PREÇO" title="Triângulo ascendente detectado" extra={<span className="badge">CONFIANÇA 82%</span>}/><div className="priceChart"><div className="resistance"><span>RESISTÊNCIA 32,10</span></div><div className="support"><span>SUPORTE ASCENDENTE</span></div><div className="candles">{candleHeights.map((h,i)=><i key={i} className={i%4===0||i%7===0?"red":"green"} style={{height:`${h}%`,transform:`translateY(${i%3*5}px)`}}><b/></i>)}</div></div><div className="chartFoot"><span><i className="dot greenDot"/>MM20</span><span><i className="dot blueDot"/>MM50</span><span>Volume <b>1,7× média</b></span></div></article>
    <article className="card thermo"><Title kicker="TERMÔMETRO DO ATIVO" title="Leitura consolidada" extra={<button className="info" title="Regras fixas, sem IA">i</button>}/><div className="scoreRing" style={{"--score":`${(score+100)*1.8}deg`} as React.CSSProperties}><div><b>{score>0?"+":""}{score}</b><span>DE 100</span></div></div><h3>{label}</h3><p>{score>=20?"Convergência positiva, com risco controlado.":"Sinais mistos: aguarde confirmação."}</p><div className="scale"><div className="scaleTrack"><i style={{left:`${(score+100)/2}%`}}/></div><div><span>-100<br/>Venda</span><span>0<br/>Neutro</span><span>+100<br/>Compra</span></div></div><div className="confidence"><span>Confiança da leitura</span><b>{confidence}%</b><div><i style={{width:`${confidence}%`}}/></div></div></article>
    <article className="card signals" id="regras"><Title kicker="RAIO-X DA NOTA" title={`${signals.length} sinais ativos`} extra={<span className="sum">SOMA: <b>{score>0?"+":""}{score}</b></span>}/><div className="signalList">{signals.map((s,i)=><button key={s[0]} onClick={()=>setOpen(open===i?null:i)} className={open===i?"opened":""}><span className={`sign ${s[2]>0?"positive":"negative"}`}>{s[2]>0?"+":""}{s[2]}</span><span className="signalText"><b>{s[0]}</b><small>{s[1]}</small>{open===i&&<em>{s[4]}</em>}</span><span className="group">{s[3]}</span><span className="chev">›</span></button>)}</div></article>
    <article className="card levels"><Title kicker="PLANO TÉCNICO" title="Cenário de referência"/><div className="level target"><span>ALVO PROJETADO</span><b>R$ 35,20</b><small>+11,9%</small></div><div className="level entry"><span>GATILHO DE ENTRADA</span><b>R$ 32,18</b><small>fechamento</small></div><div className="level stop"><span>INVALIAÇÃO / STOP</span><b>R$ 30,42</b><small>-3,3%</small></div><div className="risk"><span>RISCO : RETORNO</span><b>1 : 3,4</b></div><p className="disclaimer">Níveis calculados por estrutura e ATR. Conteúdo educacional, não é recomendação.</p></article>
   </div>
  </section>
  <section className="method" id="metodo"><div><span className="eyebrow">COMO A NOTA NASCE</span><h2>Sem palpite.<br/>Sem caixa-preta.</h2></div><div className="methodSteps">{[["01","Detectamos","Pivôs, linhas, compressões e padrões geométricos."],["02","Confirmamos","Momentum, tendência, volume e volatilidade validam o cenário."],["03","Pontuamos","Cada regra soma ou subtrai pontos com pesos públicos."],["04","Explicamos","Você audita cada ponto e sabe o que muda a leitura."]].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <footer><span><b>T°</b> TERMÔMETRO</span><p>Ferramenta educacional • Motor determinístico • Sem IA</p><small>PILOTO v0.1</small></footer>
 </main>
}
function Title({kicker,title,extra}:{kicker:string,title:string,extra?:React.ReactNode}){return <div className="cardTitle"><div><span>{kicker}</span><b>{title}</b></div>{extra}</div>}
